name = "asia-market-intelligence"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "ami-page-views"
database_id = "87e1b7f2-5e65-4b2e-aef4-136c0599e1fd"